'use strict';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS';
export const SET_PINNED = 'SET_PINNED';
export const FILTRATION = 'FILTRATION';