'use strict';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const INVALIDATE_CONVERSATION = 'INVALIDATE_CONVERSATION';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';